### ISSUE TITLE
Cleaning Readme Data

### ISSUE THREAD

**Issue by kailashchoudhary11** [Agent-Hellboy/YouTubeDataApi_Wrapper#24]
There are some typos in the Readme file and also the black colored text in the flow chart at the bottom is not readable by those who are using Night Theme!

**Comment by Agent-Hellboy** [comment]
Thanks for finding these issues. looking forward to your PR with the fix.

**Comment by sDaman830** [comment]
i would like to look into this issue

**Comment by Agent-Hellboy** [comment]
@sDaman830  you should add fixes #issuenumber to your PR description so that GitHub can link your PR to this issue
