### ISSUE TITLE
Fix sourcery issues 

### ISSUE THREAD

**Issue by BismeetSingh** [Agent-Hellboy/YouTubeDataApi_Wrapper#26]
Fix linting and code quality issues suggested by sorcery.

**Comment by tintinthong** [comment]
Hi. I would like to take this on for hacktoberfest! You are referring to https://github.com/alexmojaki/sorcery this right?

**Comment by BismeetSingh** [comment]
I am already working on it. You can create another issue if u see something

**Comment by Agent-Hellboy** [comment]
Hi @BismeetSingh, do use fixes #issuenumber in your PR description so that GitHub can link the issue with PR. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by BismeetSingh** [comment]
Okay, sure.

**Comment by Agent-Hellboy** [comment]
>Hi. I would like to take this on for hacktoberfest! You are referring to https://github.com/alexmojaki/sorcery this right?

@tintinthong No it's closed source, https://sourcery.ai/
