### ISSUE TITLE
Improve the overall design of the package

### ISSUE THREAD

**Issue by Agent-Hellboy** [Agent-Hellboy/YouTubeDataApi_Wrapper#30]
The public interface of the package is not friendly, we should decide on the APIs which should be public and private and currently some public APIs( an example API is `vid=obj.get_videoinfo()`) are returning a list of objects which should not be expected behavior. 

For first-time contributors, look into the design patterns from https://refactoring.guru/design-patterns and try to grab some ideas.

**Comment by ethmtrgt** [comment]
Hello, I'd like to work on this issue, can you please assign me?

**Comment by Agent-Hellboy** [comment]
Sure, I hope you will share your approach first, before going for the implementation.

**Comment by ethmtrgt** [comment]
Hello, I sent you an email last week. Could you please check?

**Comment by Agent-Hellboy** [comment]
sorry, let me check.

**Comment by Agent-Hellboy** [comment]
Hi @ethmtrgt, thanks for showing interest. 
>currently some public APIs( an example API is vid=obj.get_videoinfo()) are returning a list of objects which should not be expected behavior.

This is done, we are not returning a list of objects now, we are returning the generator object.

I could suggest adding new APIs to give missing metadata of the video(currently I guess we have APIs to give metadata of videos only, we could provide an API that takes channel id or name and provide metadata), then you will get some ideas to tweak the design.

here is the API Reference https://developers.google.com/youtube/v3/docs

currently, we query this class internally only to get channel info
https://github.com/Agent-Hellboy/pyytdata/blob/3ce31fc200ddec2b42c88b9edca038240e96b3f9/pyytdata/util/channelinfo.py#L6
