### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by kailashchoudhary11** [Agent-Hellboy/YouTubeDataApi_Wrapper#36]
Should we add all the requirements in the install_requires list?

**Comment by Agent-Hellboy** [comment]
Which one is missing?

**Comment by kailashchoudhary11** [comment]
I mean adding everything that's in requirements.txt

**Comment by Agent-Hellboy** [comment]
No, it's not required, all others are dependency of `google-api-python-client`

**Comment by kailashchoudhary11** [comment]
Okay
