### ISSUE TITLE
Add async support 

### ISSUE THREAD

**Issue by Agent-Hellboy** [Agent-Hellboy/YouTubeDataApi_Wrapper#38]

**Comment by BismeetSingh** [comment]
Can you provide more details

**Comment by Agent-Hellboy** [comment]
Hi @BismeetSingh thanks for your interest in the package, look at the  `obj=PyYtData('flask',10)`, here we are looking for 10 video info objects, we should return a generator objects instead of a list of video objects, this should be the first step towards async.

do you want to work on this as a hactoberfest PR?

**Comment by BismeetSingh** [comment]
Yes,on it.
